python train.py \
--name standing_cat_no_aug --batch 1 \
--dataroot_sketch data/sketch/photosketch/standing_cat \
--dataroot_image data/image/lmdb/cat --l_image 0.7 \
--g_pretrained pretrained/stylegan2-cat/netG.pth \
--d_pretrained pretrained/stylegan2-cat/netD.pth \
--max_iter 300000 --disable_eval \
--resume_iter 198000 \
--checkpoints_dir checkpoint/ \
--photosketch_path pretrained/photosketch.pth \
--display_freq 2000 \
